import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>GlowAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <div className="flex flex-col min-h-screen justify-center items-center">
        <div className="flex flex-row justify-center items-center">
          <h1 class="font-extrabold text-transparent text-8xl bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
            Glow AI
          </h1>
          <h1 className="text-8xl ml-5">🧖🏻‍♀️</h1>
        </div>
        <div>
          <h2 className="flex flex-row justify-center items-center mt-10 text-2xl">
            Enter your skin type and budget and our AI will handle the rest.
          </h2>
        </div>
      </div>
    </>
  );
}
